import { Metadata } from "next";
import { BreadcrumbSchema } from "@/components/seo/structured-data";

export const metadata: Metadata = {
  title: "Free Church Management Software | Relius Pricing",
  description:
    "Free church management software with online giving, AI-powered donation tools, and unlimited members. Free forever. Ministry Pro $60/mo, Ministry AI $150/mo for advanced features.",
  alternates: {
    canonical: "https://relius.ai/pricing/",
  },
  openGraph: {
    title: "Free Church Management Software | Relius Pricing",
    description:
      "Free church management with online giving and AI donation tools. Unlimited members, no credit card required. Upgrade for pastoral care and AI features.",
    url: "https://relius.ai/pricing/",
    images: [{ url: "/og-image.png", width: 1200, height: 630, alt: "Relius Pricing Plans" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "Free Church Management Software | Relius Pricing",
    description:
      "Free church management with online giving and AI donation tools. Unlimited members, no credit card required. Upgrade for pastoral care and AI features.",
  },
};

export default function PricingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <BreadcrumbSchema items={[
        { name: "Home", url: "https://relius.ai/" },
        { name: "Pricing", url: "https://relius.ai/pricing/" },
      ]} />
            <script
                      type="application/ld+json"
                                dangerouslySetInnerHTML={{
                                            __html: JSON.stringify({
                                                            "@context": "https://schema.org",
                                                                          "@type": "FAQPage",
                                                                                        mainEntity: [
                                                                                                        {
                                                                                                                          "@type": "Question",
                                                                                                                                            name: "Is the Free plan really free forever?",
                                                                                                                                                              acceptedAnswer: {
                                                                                                                                                                                  "@type": "Answer",
                                                                                                                                                                                                      text: "Yes! The Free plan includes full church management, online giving, and AI-powered donation tools at no monthly cost. We only charge processing fees on donations.",
                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                          "@type": "Question",
                                                                                                                                                                                                                                                                                            name: "How do processing fees work?",
                                                                                                                                                                                                                                                                                                              acceptedAnswer: {
                                                                                                                                                                                                                                                                                                                                  "@type": "Answer",
                                                                                                                                                                                                                                                                                                                                                      text: "Processing fees only apply to donations made through the platform. Credit/Debit cards are charged 2% + $0.19 per transaction. ACH transfers are $0.19 flat.",
                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                          "@type": "Question",
                                                                                                                                                                                                                                                                                                                                                                                                                                            name: "How do I know which plan is right for our church?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              acceptedAnswer: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "@type": "Answer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      text: "Start with Free - it includes everything most churches need to get started, including online giving with AI-powered tools. Upgrade to Ministry Pro if you need advanced analytics or pastoral care features.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "@type": "Question",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            name: "Can I switch plans later?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              acceptedAnswer: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  "@type": "Answer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      text: "Absolutely! You can upgrade or downgrade at any time. Your data is always preserved when switching between plans.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
      {children}
    </>
  );
}
